import { Profile, UIConversation, UIMessage, UserSettings } from '../types/chat.types';

export const CURRENT_USER: Profile = {
  id: 'usr_me_001',
  username: 'alex_dev',
  display_name: 'Alex Rivera',
  avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  bio: 'Full-stack engineer & open sourcerer. Building fast real-time software.',
  phone: '+1 (555) 349-2049',
  status_text: 'Coding in flow ⚡',
  is_online: true,
  last_seen_at: new Date().toISOString(),
  created_at: new Date(Date.now() - 90 * 24 * 3600 * 1000).toISOString(),
  updated_at: new Date().toISOString(),
};

export const ADMIN_USER: Profile = {
  id: 'usr_admin_master',
  username: 'admin',
  display_name: 'Platform Admin',
  avatar_url: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
  bio: 'Platform Administrator with master moderation, access control, and system management privileges.',
  phone: '+1 (555) 019-9832',
  status_text: 'Admin Console Active 🛡️',
  is_online: true,
  last_seen_at: new Date().toISOString(),
  created_at: new Date(Date.now() - 120 * 24 * 3600 * 1000).toISOString(),
  updated_at: new Date().toISOString(),
};

export const MOCK_USERS: Profile[] = [
  {
    id: 'usr_paddy_ai',
    username: 'paddy_ai',
    display_name: 'Paddy AI',
    avatar_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=150&auto=format&fit=crop&q=80',
    bio: 'Your personal AI co-pilot on ChatPaddy. Ask me questions, summarize threads, or search knowledge.',
    phone: null,
    status_text: 'Always ready to help ✨',
    is_online: true,
    last_seen_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'usr_ada_002',
    username: 'ada_code',
    display_name: 'Ada Lovelace',
    avatar_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    bio: 'Software Architect. Loving clean code, distributed systems, and real-time websockets.',
    phone: '+1 (555) 234-8712',
    status_text: 'Reviewing PRs 💻',
    is_online: true,
    last_seen_at: new Date().toISOString(),
    created_at: new Date(Date.now() - 60 * 24 * 3600 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'usr_chidi_003',
    username: 'chidi_ethics',
    display_name: 'Chidi Anagonye',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    bio: 'Engineering ethics, security compliance, and robust API contracts.',
    phone: '+1 (555) 890-4411',
    status_text: 'In deep focus 📚',
    is_online: true,
    last_seen_at: new Date().toISOString(),
    created_at: new Date(Date.now() - 45 * 24 * 3600 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'usr_zainab_004',
    username: 'zainab_ux',
    display_name: 'Zainab Bello',
    avatar_url: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=150&auto=format&fit=crop&q=80',
    bio: 'Lead Product Designer. Making interfaces effortless, accessible, and delightful.',
    phone: '+234 802 334 9102',
    status_text: 'Design review mode 🎨',
    is_online: false,
    last_seen_at: new Date(Date.now() - 14 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 30 * 24 * 3600 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'usr_marcus_005',
    username: 'marcus_dev',
    display_name: 'Marcus Chen',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    bio: 'DevOps & Cloud infrastructure engineer. Kubernetes, Edge Functions, and latency.',
    phone: '+1 (555) 761-9032',
    status_text: 'Deploying release 0.9.4 🚀',
    is_online: false,
    last_seen_at: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
    created_at: new Date(Date.now() - 20 * 24 * 3600 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const INITIAL_CONVERSATIONS: UIConversation[] = [
  {
    id: 'conv_ada_direct',
    type: 'direct',
    name: 'Ada Lovelace',
    avatar_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    description: 'Software Architect',
    is_pinned: true,
    is_archived: false,
    is_muted: false,
    unread_count: 2,
    last_message_at: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    last_message_preview: 'I just benchmarked the Supabase Realtime channel latency!',
    last_message_status: 'delivered',
    last_message_is_mine: false,
    other_user: MOCK_USERS[1],
    participants: [
      {
        conversation_id: 'conv_ada_direct',
        user_id: CURRENT_USER.id,
        role: 'member',
        last_read_at: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
        is_pinned: true,
        is_archived: false,
        is_muted: false,
        joined_at: new Date().toISOString(),
      },
      {
        conversation_id: 'conv_ada_direct',
        user_id: MOCK_USERS[1].id,
        role: 'member',
        last_read_at: new Date().toISOString(),
        is_pinned: false,
        is_archived: false,
        is_muted: false,
        joined_at: new Date().toISOString(),
        profile: MOCK_USERS[1],
      },
    ],
  },
  {
    id: 'conv_paddy_ai_direct',
    type: 'direct',
    name: 'Paddy AI',
    avatar_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=150&auto=format&fit=crop&q=80',
    description: 'AI Assistant & Copilot',
    is_pinned: true,
    is_archived: false,
    is_muted: false,
    unread_count: 0,
    last_message_at: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    last_message_preview: 'Here is a quick summary of the database migration checklist.',
    last_message_status: 'read',
    last_message_is_mine: false,
    other_user: MOCK_USERS[0],
    participants: [
      {
        conversation_id: 'conv_paddy_ai_direct',
        user_id: CURRENT_USER.id,
        role: 'member',
        last_read_at: new Date().toISOString(),
        is_pinned: true,
        is_archived: false,
        is_muted: false,
        joined_at: new Date().toISOString(),
      },
      {
        conversation_id: 'conv_paddy_ai_direct',
        user_id: MOCK_USERS[0].id,
        role: 'member',
        last_read_at: new Date().toISOString(),
        is_pinned: false,
        is_archived: false,
        is_muted: false,
        joined_at: new Date().toISOString(),
        profile: MOCK_USERS[0],
      },
    ],
  },
  {
    id: 'conv_team_group',
    type: 'group',
    name: 'ChatPaddy Core Team',
    avatar_url: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=150&auto=format&fit=crop&q=80',
    description: 'Engineering, design, and roadmap synchronization.',
    is_pinned: false,
    is_archived: false,
    is_muted: false,
    unread_count: 0,
    last_message_at: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
    last_message_preview: 'Zainab: The new UI system looks super crisp!',
    last_message_status: 'read',
    last_message_is_mine: false,
    group_meta: {
      conversation_id: 'conv_team_group',
      name: 'ChatPaddy Core Team',
      description: 'Engineering, design, and roadmap synchronization.',
      avatar_url: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=150&auto=format&fit=crop&q=80',
      created_by: CURRENT_USER.id,
      created_at: new Date(Date.now() - 30 * 24 * 3600 * 1000).toISOString(),
    },
    participants: [
      { conversation_id: 'conv_team_group', user_id: CURRENT_USER.id, role: 'owner', last_read_at: new Date().toISOString(), is_pinned: false, is_archived: false, is_muted: false, joined_at: new Date().toISOString(), profile: CURRENT_USER },
      { conversation_id: 'conv_team_group', user_id: MOCK_USERS[1].id, role: 'admin', last_read_at: new Date().toISOString(), is_pinned: false, is_archived: false, is_muted: false, joined_at: new Date().toISOString(), profile: MOCK_USERS[1] },
      { conversation_id: 'conv_team_group', user_id: MOCK_USERS[2].id, role: 'member', last_read_at: new Date().toISOString(), is_pinned: false, is_archived: false, is_muted: false, joined_at: new Date().toISOString(), profile: MOCK_USERS[2] },
      { conversation_id: 'conv_team_group', user_id: MOCK_USERS[3].id, role: 'member', last_read_at: new Date().toISOString(), is_pinned: false, is_archived: false, is_muted: false, joined_at: new Date().toISOString(), profile: MOCK_USERS[3] },
    ],
  },
  {
    id: 'conv_zainab_direct',
    type: 'direct',
    name: 'Zainab Bello',
    avatar_url: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=150&auto=format&fit=crop&q=80',
    description: 'Lead Product Designer',
    is_pinned: false,
    is_archived: false,
    is_muted: false,
    unread_count: 0,
    last_message_at: new Date(Date.now() - 22 * 3600 * 1000).toISOString(),
    last_message_preview: '📎 Shared design-system-tokens-v2.fig',
    last_message_status: 'read',
    last_message_is_mine: false,
    other_user: MOCK_USERS[3],
    participants: [
      { conversation_id: 'conv_zainab_direct', user_id: CURRENT_USER.id, role: 'member', last_read_at: new Date().toISOString(), is_pinned: false, is_archived: false, is_muted: false, joined_at: new Date().toISOString() },
      { conversation_id: 'conv_zainab_direct', user_id: MOCK_USERS[3].id, role: 'member', last_read_at: new Date().toISOString(), is_pinned: false, is_archived: false, is_muted: false, joined_at: new Date().toISOString(), profile: MOCK_USERS[3] },
    ],
  },
  {
    id: 'conv_chidi_direct',
    type: 'direct',
    name: 'Chidi Anagonye',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    description: 'System Architecture',
    is_pinned: false,
    is_archived: false,
    is_muted: true,
    unread_count: 0,
    last_message_at: new Date(Date.now() - 48 * 3600 * 1000).toISOString(),
    last_message_preview: 'Let us confirm the RLS security policies before deploying.',
    last_message_status: 'read',
    last_message_is_mine: true,
    other_user: MOCK_USERS[2],
    participants: [
      { conversation_id: 'conv_chidi_direct', user_id: CURRENT_USER.id, role: 'member', last_read_at: new Date().toISOString(), is_pinned: false, is_archived: false, is_muted: true, joined_at: new Date().toISOString() },
      { conversation_id: 'conv_chidi_direct', user_id: MOCK_USERS[2].id, role: 'member', last_read_at: new Date().toISOString(), is_pinned: false, is_archived: false, is_muted: false, joined_at: new Date().toISOString(), profile: MOCK_USERS[2] },
    ],
  },
];

export const INITIAL_MESSAGES: Record<string, UIMessage[]> = {
  conv_ada_direct: [
    {
      id: 'msg_ada_1',
      conversation_id: 'conv_ada_direct',
      sender_id: 'usr_ada_002',
      content: 'Hey Alex! Did you get a chance to inspect the new Supabase database migration script?',
      type: 'text',
      reply_to_id: null,
      forwarded_from: null,
      edited_at: null,
      deleted_at: null,
      deleted_for_everyone: false,
      created_at: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
      sender: MOCK_USERS[1],
      receipt_status: 'read',
      reactions: {
        '👍': { count: 1, users: ['usr_me_001'], userReacted: true },
      },
    },
    {
      id: 'msg_me_2',
      conversation_id: 'conv_ada_direct',
      sender_id: 'usr_me_001',
      content: 'Yes! The RLS policies with security definer functions look rock solid. No recursion issues at all.',
      type: 'text',
      reply_to_id: 'msg_ada_1',
      forwarded_from: null,
      edited_at: null,
      deleted_at: null,
      deleted_for_everyone: false,
      created_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
      sender: CURRENT_USER,
      receipt_status: 'read',
      reactions: {
        '🔥': { count: 1, users: ['usr_ada_002'], userReacted: false },
      },
    },
    {
      id: 'msg_ada_3',
      conversation_id: 'conv_ada_direct',
      sender_id: 'usr_ada_002',
      content: 'Check out the clean architecture diagram we built for real-time presence and typing broadcast:',
      type: 'text',
      reply_to_id: null,
      forwarded_from: null,
      edited_at: null,
      deleted_at: null,
      deleted_for_everyone: false,
      created_at: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
      sender: MOCK_USERS[1],
      receipt_status: 'read',
    },
    {
      id: 'msg_ada_4_img',
      conversation_id: 'conv_ada_direct',
      sender_id: 'usr_ada_002',
      content: 'Architecture overview diagram',
      type: 'image',
      reply_to_id: null,
      forwarded_from: null,
      edited_at: null,
      deleted_at: null,
      deleted_for_everyone: false,
      created_at: new Date(Date.now() - 24 * 60 * 1000).toISOString(),
      sender: MOCK_USERS[1],
      receipt_status: 'read',
      attachments: [
        {
          id: 'att_img_1',
          message_id: 'msg_ada_4_img',
          storage_path: 'attachments/architecture_diagram.jpg',
          file_name: 'ChatPaddy_Realtime_Architecture.jpg',
          mime_type: 'image/jpeg',
          size: 1420500,
          duration: null,
          created_at: new Date(Date.now() - 24 * 60 * 1000).toISOString(),
        },
      ],
    },
    {
      id: 'msg_ada_5_voice',
      conversation_id: 'conv_ada_direct',
      sender_id: 'usr_ada_002',
      content: '',
      type: 'voice',
      reply_to_id: null,
      forwarded_from: null,
      edited_at: null,
      deleted_at: null,
      deleted_for_everyone: false,
      created_at: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
      sender: MOCK_USERS[1],
      receipt_status: 'read',
      attachments: [
        {
          id: 'att_voice_1',
          message_id: 'msg_ada_5_voice',
          storage_path: 'voice/voice_note_1.webm',
          file_name: 'Voice Note (0:14)',
          mime_type: 'audio/webm',
          size: 42800,
          duration: 14,
          created_at: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
        },
      ],
    },
    {
      id: 'msg_ada_6',
      conversation_id: 'conv_ada_direct',
      sender_id: 'usr_ada_002',
      content: 'I just benchmarked the Supabase Realtime channel latency! Sub-40ms end-to-end delivery.',
      type: 'text',
      reply_to_id: null,
      forwarded_from: null,
      edited_at: null,
      deleted_at: null,
      deleted_for_everyone: false,
      created_at: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
      sender: MOCK_USERS[1],
      receipt_status: 'delivered',
    },
  ],
  conv_paddy_ai_direct: [
    {
      id: 'msg_ai_1',
      conversation_id: 'conv_paddy_ai_direct',
      sender_id: 'usr_paddy_ai',
      content: `Hello Alex! 👋 Welcome to ChatPaddy.
"Chat like friends. Build like pros."

I am **Paddy AI**, your built-in intelligent companion. Here are some things I can do for you:
1. **Summarize unread threads or conversations** in 1 click
2. **Suggest smart contextual replies**
3. **Perform semantic search** over conversations
4. **Answer questions about engineering, APIs, design**, or write code snippets

Try asking me anything or click the AI summary button on any chat!`,
      type: 'text',
      reply_to_id: null,
      forwarded_from: null,
      edited_at: null,
      deleted_at: null,
      deleted_for_everyone: false,
      created_at: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
      sender: MOCK_USERS[0],
      receipt_status: 'read',
    },
    {
      id: 'msg_ai_2',
      conversation_id: 'conv_paddy_ai_direct',
      sender_id: 'usr_me_001',
      content: 'What makes ChatPaddy different from existing chat apps?',
      type: 'text',
      reply_to_id: null,
      forwarded_from: null,
      edited_at: null,
      deleted_at: null,
      deleted_for_everyone: false,
      created_at: new Date(Date.now() - 50 * 60 * 1000).toISOString(),
      sender: CURRENT_USER,
      receipt_status: 'read',
    },
    {
      id: 'msg_ai_3',
      conversation_id: 'conv_paddy_ai_direct',
      sender_id: 'usr_paddy_ai',
      content: `Great question! Here is what makes ChatPaddy stand out:

- **Original Product & Brand Identity**: Custom Paddy Indigo palette, signature speech-bubble "P" logo, and tailored developer-first ergonomics.
- **Enterprise-Grade Database Architecture**: Complete PostgreSQL schema with RLS on every table, security definer helpers, and full-text search indexing.
- **Real-Time Synergy**: Postgres change streams + Presence for online statuses + Broadcast for instant typing indicators.
- **Integrated AI Intelligence**: Server-side Gemini Edge Function powering thread summarization, smart replies, and semantic search.
- **Rich Media & WebRTC**: Voice messaging with interactive waveforms, attachments, reactions, quotes, and call signalling.`,
      type: 'text',
      reply_to_id: 'msg_ai_2',
      forwarded_from: null,
      edited_at: null,
      deleted_at: null,
      deleted_for_everyone: false,
      created_at: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
      sender: MOCK_USERS[0],
      receipt_status: 'read',
      reactions: {
        '🚀': { count: 1, users: ['usr_me_001'], userReacted: true },
        '❤️': { count: 1, users: ['usr_me_001'], userReacted: true },
      },
    },
  ],
  conv_team_group: [
    {
      id: 'msg_group_1',
      conversation_id: 'conv_team_group',
      sender_id: 'usr_me_001',
      content: 'Welcome everyone to the ChatPaddy Core Team channel! 🚀',
      type: 'text',
      reply_to_id: null,
      forwarded_from: null,
      edited_at: null,
      deleted_at: null,
      deleted_for_everyone: false,
      created_at: new Date(Date.now() - 10 * 3600 * 1000).toISOString(),
      sender: CURRENT_USER,
      receipt_status: 'read',
    },
    {
      id: 'msg_group_2',
      conversation_id: 'conv_team_group',
      sender_id: 'usr_chidi_003',
      content: 'Glad to be here. I reviewed the SQL schema; the foreign keys with cascading delete rules protect data integrity.',
      type: 'text',
      reply_to_id: null,
      forwarded_from: null,
      edited_at: null,
      deleted_at: null,
      deleted_for_everyone: false,
      created_at: new Date(Date.now() - 6 * 3600 * 1000).toISOString(),
      sender: MOCK_USERS[2],
      receipt_status: 'read',
    },
    {
      id: 'msg_group_3',
      conversation_id: 'conv_team_group',
      sender_id: 'usr_zainab_004',
      content: 'The new UI system looks super crisp! Love the Indigo + Amber Spark branding.',
      type: 'text',
      reply_to_id: null,
      forwarded_from: null,
      edited_at: null,
      deleted_at: null,
      deleted_for_everyone: false,
      created_at: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
      sender: MOCK_USERS[3],
      receipt_status: 'read',
      reactions: {
        '🙌': { count: 2, users: ['usr_me_001', 'usr_ada_002'], userReacted: true },
      },
    },
  ],
};

export const INITIAL_USER_SETTINGS: UserSettings = {
  user_id: CURRENT_USER.id,
  theme: 'system',
  sound_enabled: true,
  read_receipts_enabled: true,
  last_seen_privacy: 'everyone',
  avatar_privacy: 'everyone',
  updated_at: new Date().toISOString(),
};
